### ISSUE TITLE
Internal 500 Error when open /schedule/month

### ISSUE THREAD

**Issue by mattyy21** [drupal-modules/booking_timeslots#30]
In Drupal log show this error:

Notice: Trying to get property of non-object in template_preprocess_example_booking_general() (line 463 of /home/wlihefra/public_html/time/trunk/sites/all/modules/custom/example_booking/example_booking.theme.inc).

How can I fix?

**Comment by kenorb** [comment]
It's just a notice. You can disable the notices in the configuration or check line 463 of your code. It seems you've actually copied the code and using different filenames, so I'm not sure to which code it relates to.
